[AURON #2047] Fix Scala 2.13 CI NoClassDefFoundError (#2048)
# Which issue does this PR close?

Closes #2047

# Rationale for this change

```bash
  if [ 2.13 = "2.13" && "spark-3.5" != "spark-4.0" && "spark-3.5" != "spark-4.1" ]; then
    SPARK_FILE="spark-3.5.8-bin-hadoop3-scala2.13.tgz"
  else
    SPARK_FILE="spark-3.5.8-bin-hadoop3.tgz"
  fi
```

```
/home/runner/work/_temp/5e39dd44-8905-4fc9-ad30-a316cba0dc50.sh: line 2: [: missing `]'
--2026-02-27 05:16:45--  https://www.apache.org/dyn/closer.lua/spark/spark-3.5.8/spark-3.5.8-bin-hadoop3.tgz?action=download
```


https://github.com/apache/auron/actions/runs/22473356538/job/65096490529?pr=2040


# What changes are included in this PR?

# Are there any user-facing changes?

# How was this patch tested?
GHA

```
--2026-02-27 13:27:10--  https://www.apache.org/dyn/closer.lua/spark/spark-3.5.8/spark-3.5.8-bin-hadoop3-scala2.13.tgz?action=download
```